#!/bin/bash
set -e

cd /rus

wget http://biogeo.ucdavis.edu/data/gadm2/shp/RUS_adm.zip
unzip RUS_adm.zip

ogr2ogr -f GeoJSON subunits.json RUS_adm1.shp
topojson -e RUS_adm2.csv -p -o russia.json subunits.json
rm subunits.json

ogr2ogr -where "ID_1 IN ('48')"  -f GeoJSON districts.json RUS_adm3.shp
topojson -e RUS_adm3.csv -p -o moscow.json districts.json
rm districts.json
